<?php require('templates/header.php'); ?>
<?php require('templates/offcanvas.php'); ?>
<?php require('templates/hero.php'); ?>
<?php require('templates/welcome.php'); ?>
<?php require('templates/about.php') ?>
<?php require('templates/skills.php'); ?>
<?php require('templates/portfolio.php'); ?>
<?php require('templates/contact.php'); ?>
<?php require('templates/footer.php'); ?>